### ISSUE TITLE
Enable `Reindex Content` job automatically on UI nodes

### ISSUE THREAD

**Issue by p-kimberley** [gradata-systems/stroom-k8s-operator#53]
This will assist users by having the index available on first search and updating it periodically thereafter.

**Comment by p-kimberley** [comment]
To provide more flexibility and accommodate future node job types, an alternative is to allow the user to limit which jobs are "managed" automatically through a new field: `StroomCluster.nodeSet.managedJobs`.

For instance, a `NodeSet` of type `Processing` might be assigned:
```yaml
spec:
  managedJobs:
    - Data Processor
    - Processor Task Creator
```
Such a node would enable these tasks on startup and disable them prior to shutdown (to enable it to drain active tasks then gracefully terminate).

Meanwhile a `Frontend` node might have:
```yaml
spec:
  managedJobs:
    - Reindex Content
```
